import = [
  "~/.config/alacritty/themes/catppuccin-macchiato.toml",
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[font]
size = 15.0

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
lf
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002T"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = """
tmux
"""
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002u"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToFile
"""
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToCommand
"""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:q
"""
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002p"
key = "`"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command|Shift"

[scrolling]
history = 10000

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = false
opacity = 1
option_as_alt = "Both"
title = "one thing well"

[window.padding]
x = 25
y = 20
